WIP Add internal_lb to interface
juju-solutions/interface-openstack-integration pull request #12
Opened 2022-04-07 01:18 UTC by swalladge

This is so internal-lb con be configured in charm-openstack-integrator,
and the value passed to charm-kubernetes-control-plane
via this interface
to be used in the config for cloud-provider-openstack.

Note that the code that reads this internal_lb value
is actually in layer-kubernetes-common (python library).
charm-kubernetes-control-plane calls functions from that library.

2022-04-07 05:53 UTC, swalladge commented on provides.py
> +                         internal_lb,
Flagging this as a backwards incompatible change.  How should incompatible changes be handled?  I don't see any kind of revision pinning for interfaces; as far as I can work out, any run of charm-build is going to read https://github.com/juju/layer-index/blob/master/interfaces/openstack-integration.json and pull the master branch of this repo.

2022-04-20 13:10 UTC, addyess requested changes

2022-04-20 13:10 UTC, addyess commented on provides.py
> +                         internal_lb,
well, I guess for backwards compatibility, couldn't this become

```python
    def set_lbaas_config(self,
                         subnet_id,
                         floating_network_id,
                         lb_method,
                         manage_security_groups,
                         has_octavia=None
                         internal_lb=False):
```

2022-04-21 02:15 UTC, addyess approved these changes
yah!

2022-04-21 02:16 UTC, addyess commented on requires.py
> +        return self._received['internal_lb'] or False
actually, this may not ALWAYS be in the relation data right (ie -- during a charm upgrade)

```suggestion
        return self._received.get('internal_lb',  False)
```

2022-04-21 04:24 UTC, swalladge commented on requires.py
> +        return self._received['internal_lb'] or False
Oh good catch :+1:

2022-04-21 08:28 UTC, swalladge commented
Note: don't merge yet; I'm still testing the latest changes.

2022-04-22 00:44 UTC, swalladge commented
Ok, testing finished from my end.  Ready for another review pass. :)

2022-04-22 14:43 UTC, merged